### ISSUE TITLE
Relationship with Htmx?

### ISSUE THREAD

**Issue by leomcelroy** [bigskysoftware/_hyperscript#113]
Really interesting project! 

Could you clarify the relationship with Htmx? I see you call it a companion project but I'm not entirely sure what that means. 

This would help people like myself who are interested in both but want to understand where they are headed before committing time to one.

**Comment by 1cg** [comment]
htmx grew out of intercooler, which had a simple system for defining client actions, `ic-action` that was the initial seed for hyperscript, with it's `wait` clause:

https://intercoolerjs.org/attributes/ic-action.html

There were some other attributes to support scripting from intercooler, and I didn't like how messy and specific it all was.

I spell things out a bit more here:

https://htmx.org/docs/#hyperscript

In general, htmx is a solid idea and has a solid implementation, whereas I'm being a bit more speculative and ambitious with hyperscript.  They play well together, by design, but aren't bound to one another, so if you don't want to deal with the hyperscript insanity, you can just use htmx and whatever other scripting solution you like.  :)

**Comment by leomcelroy** [comment]
Thank you! That's helpful, keep up the good work.
