### ISSUE TITLE
composability/encapsulation?

### ISSUE THREAD

**Issue by swizzard** [bigskysoftware/_hyperscript#17]
Is it possible to compose/encapsulate commands? it'd be nice to be able to do something like `_="on blur validate-email me"` rather than writing out a whole regex every time, especially if some email inputs have additional logic.

**Comment by 1cg** [comment]
right now, no, the only feature in the grammar is reactive `on` statements

i am planning on implementing more features in the next few months though, with htmx 1.0 wrapping up

in the meantime, you could call out to javascript like so:

```html
<input _="on blur call validateEmail(me)" ...>
```
also note that the latest version of htmx supports the HTML validation API, so that might be another approach for this particular problem:

https://htmx.org/docs/#validation
