### ISSUE TITLE
show does not display table rows correctly

### ISSUE THREAD

**Issue by iamjameswalters** [bigskysoftware/_hyperscript#186]
### Issue:
`show` applies `display: block` to table rows, but should be `display: table-row`. Trying `show:table-row` throws a parsing error.

### Bug:
`show:[argument]` syntax should be fixed.

### Feature Request:
[jQuery's .hide()](https://api.jquery.com/hide/#entry-longdesc) caches the element's `display` value and resets it to this value on `.show()`. This would be my expected behavior.

### Demonstrations:

* [Fiddle showing `show` applying `display: block`](https://jsfiddle.net/5hmcx0nd/8/)
* [Fiddle showing `show:table-row` throwing error](https://jsfiddle.net/58bnp7w2/)
* [Fiddle replacing `show` with `set ___.style.display to 'table-row'` working with expected behavior](https://jsfiddle.net/p734qtdf/0)

**Comment by dz4k** [comment]
> `show:[argument]` syntax should be fixed.

The syntax is `show element with display:table-row`. The second jsfiddle you sent works with this syntax.

**Comment by benpate** [comment]
Thanks for filing this issue.  To echo what @1cg said on Discord, it would be best for _hyperscript to automatically handle the specific *kind* of display.  So, following jQuery's example and somehow capturing the original display so that it could be restored later.

Any changes we make for this issue should also apply to `toggle` as well.

**Comment by dz4k** [comment]
`transition` captures the original value to make `transition my whatever to initial` work, so it should be doable. We could also decide the display value to use based on the tag name (table-row for tr, block for p, inline for em etc.)
