### ISSUE TITLE
v0.9.7 - distributed script breaks in Safari

### ISSUE THREAD

**Issue by croxton** [bigskysoftware/_hyperscript#334]
When using the script in`/dist/` directly in the browser (via `https://unpkg.com/hyperscript.org@0.9.7`), an error is thrown in Safari 14 and 15 breaking some (but not all) functionality. 

This line throws an unexpected token error:
https://github.com/bigskysoftware/_hyperscript/blob/054e04667497f204aff0a7ebfa5a1325a8adb277/dist/_hyperscript.js#L83

v0.9.5 was working previously.

**Comment by rozek** [comment]
(Disclaimer: I'm a complete \_hyperscript newbie myself!)

I just ran into the same problem. It is caused by the fact, that older Safari version do not support `static` fields in classes.

As a consequence, I've forked the original code base and am now trying to "convert" the JS code into TypeScript, as that can produce JavaScript output which rans on older devices and browsers, but still offers modern JS features to the programmer.

Let us see if I succeed...

**Comment by rozek** [comment]
Well,

I may have fixed the problem. Could you please test it as well, just by using

```
<script src="https://unpkg.com/hyperscript-experimental"></script>
```

instead of the normal script file?

**Comment by netaisllc** [comment]
Reported again here https://github.com/bigskysoftware/_hyperscript/issues/369 -- sorry I missed this one.  FWIW I concur with the analysis given above.

**Comment by 1cg** [comment]
I will try to get this fixed this week, sorry for the issue.

**Comment by 1cg** [comment]
are we far enough along that this isn't an issue?
