### ISSUE TITLE
[Bug] default actions are not prevented by halt/exit

### ISSUE THREAD

**Issue by rozek** [bigskysoftware/_hyperscript#342]
I wrote a [live example](https://svelte.dev/repl/2bee3d601e04425e80673c51331a243a) in order to verify the behaviour of `halt` and `exit` (as the [docs](https://hyperscript.org/commands/halt/) seem to be wrong, presumably, because of cut-and-paste actions)

The outcome: event defaults seem _never_ to be prevented (try checkboxes \#2, \#4, \#5, \#7 and \#8)

**Comment by 1cg** [comment]
It turns out that this is correct behavior: `preventDefault()` doesn't prevent checking the checkbox in the `input` event.  Rather, you have to do it in the `click` event.  You can verify this by using inline handlers w/ vanilla javascript:

```html

	<input type="checkbox" _="on input halt"/>
	<input type="checkbox" oninput="event.preventDefault()"/>

	<input type="checkbox" _="on click halt"/>
	<input type="checkbox" onclick="event.preventDefault()"/>
```

The `halt` command does invoke `preventDefault()` (depending on the exact syntax you use), as you can see here:

https://github.com/bigskysoftware/_hyperscript/blob/master/src/_hyperscript.js#L4989
