### ISSUE TITLE
[Bug] homepage demo on macOS Safari results in "undefined" copied to clipboard

### ISSUE THREAD

**Issue by aehlke** [bigskysoftware/_hyperscript#348]
Safari on macOS Monterey, when I use the demo on this project's homepage and click the "Copy" button, the result is "undefined" showing up in my clipboard instead of any innertext as expected.

**Comment by rozek** [comment]
(disclaimer: I'm a complete \_hyperscript newbie and may therefore be terribly wrong)

It seems that there is now HTML element with the id 'snippet' which is why there is also no `innerText` - actually, the example demonstrates the "null safety" (and its potential drawbacks) quite well.

Just changing `#snippet` to `#sample` should "repair" the example (as it has the id "sample" itself)

**Comment by rozek** [comment]
I've just changed the documentation source in order to fix this problem (and created a pull request) - but right now, I don't know how to build the docs.

We will thus have to wait for the author to finally fix this problem.
