### ISSUE TITLE
If/else chaining requires multiple "end" keywords

### ISSUE THREAD

**Issue by jkseppan** [bigskysoftware/_hyperscript#364]
The documentation says "You can chain if/else commands together in the usual manner." I understand "the usual manner" is to either allow "if ... else if ... else if ... else ... end" or to have a separate "elif", "elsif", "elseif" or similar keyword for chaining. Instead of chaining, the Hyperscript implementation seems to require nesting. Because "end" can sometimes but not always be elided, this is not always clear but can result in parse errors in following code.

Example: https://jsfiddle.net/_jks/hsqtw243/

This outputs an error message in the console that includes "Expected 'end' but found 'catch'".

Fixed example: https://jsfiddle.net/_jks/hsqtw243/3/

Note how the "end end" allows parsing to continue as a clue that the statements are nested instead of chained.

**Comment by 1cg** [comment]
Good catch!  I think the problem is that we aren't considering `catch` a command boundary here:

https://github.com/bigskysoftware/_hyperscript/blob/3c97a4a033303c11dfe742330f5c84ea483316f6/src/_hyperscript.js#L1296

so it isn't allowing the normal eliding logic to work properly.  I will get a test in an fix it for the next release.

Thank you for working with hyperscript!

**Comment by 1cg** [comment]
fixed w/ https://github.com/bigskysoftware/_hyperscript/commit/8eec50985755d5c25fadb0708d4546ce0ad1b4c8
