### ISSUE TITLE
Add new show/hide strategy using hidden attribute

### ISSUE THREAD

**Issue by spand** [bigskysoftware/_hyperscript#441]
For my recent project we have started to use the hidden attribute instead of the nastyness that is display css property. It effectively solves the problem with display that there are multiple "visible" values (that _hyperscript sort of sidesteps by assuming `block` is good enough).

Has this been considered? Seems so good that it ought to be the default.

Also seems to have support in ancient browsers:
https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/hidden
https://caniuse.com/hidden

**Comment by metametadata** [comment]
> that _hyperscript sort of sidesteps by assuming `block` is good enough

Although it's not mentioned in the [documentation](https://hyperscript.org/commands/show/), in practice the lib seems to set the original `display` value (i.e. it's not hardcoded to `block`) on calling `show` after `hide`. This seems to be the relevant source:

https://github.com/bigskysoftware/_hyperscript/blob/c82557353ad557951a4afb8c5c406909141619ab/src/_hyperscript.js#L6494

> Seems so good that it ought to be the default.

Not sure it should be default because elements with explicit `display` set will not be hidden by adding `hidden` attribute. See https://meowni.ca/hidden.is.a.lie.html and https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/hidden#the_hidden_state.

**Comment by spand** [comment]
That is tragic.

That weakens the argument a bit, and silly me for relying on the documentation instead of reading the code ;-)

Reading the code it seems that the work is dealing with the style attribute and computed styles. Not sure it is worth it to add it as a strategy then since the normal toggle is better/shorter `on click toggle [@hidden] on .dropdown`

I still feel it is a superior strategy when not working with elements that have an explicit `display` since:
* Works with CSP
* Simpler and more than generating styles

Maybe the best solution is just to mention it as an alternative in the docs for show/hide ?

**Comment by scrhartley** [comment]
I still like this feature when considering the [Filter A Group Of Elements](https://hyperscript.org/cookbook/#60-filter-a-group-of-elements) example from the cookbook:
```html
<input type="text" placeholder="Search Quotes..."
     _="on keyup
         if the event's key is 'Escape'
           set my value to ''
           trigger keyup
         else
          show <blockquote/> in #quotes when its textContent contains my value">
```

I think this would look something like:
```js
{
    hidden: function (op, element, arg) {
        if (op === "toggle") {
            if (element.hasAttribute("hidden")) {
                HIDE_SHOW_STRATEGIES.hidden("show", element, arg);
            } else {
                HIDE_SHOW_STRATEGIES.hidden("hide", element, arg);
            }
        } else if (op === "hide") {
            element.setAttribute("hidden", "");
        } else {
            element.removeAttribute("hidden");
        }
    }
}
```
