### ISSUE TITLE
string interpolation surprise

### ISSUE THREAD

**Issue by vahp** [bigskysoftware/_hyperscript#561]
backtick string interpolation fails depending on what character appears in front of the $ sign - seems to happen whether using curly-braces or not.   The docs don't mention this and javascript doesn't have this behavior.  

``<div _="init set x to 42 then put `test $x test$x test_$x test_${x} test-$x test.$x` into me"></div>``

in the https://hyperscript.org/playground/ this gets:

> test 42 test$x test_$x test_${x} test-42 test.42

**Comment by BirdeeHub** [comment]
The error is in the Lexer.tokenize function

When it finds a template string (strings surrounded with ` chars) it calls tokenize again on that string with template == true.

When it does so, it seems to parse things like test$x as a single token rather than 3

Im a noob, so, no promises, but armed with the following test and some console.logs I can hopefully prevail.

```js
	it("string interpolation isnt surprising", function () {
		var div = make( '<div _="on click set x to 42 then put `test $x test$x test_$x test_${x} test-$x test.$x` into my.innerHTML"></div>');
		div.click();
		div.innerHTML.should.equal("test 42 test42 test_42 test_42 test-42 test.42");
	});
```

Ill poke at it when I have free time and get tired of doing other stuff this week because language stuff is fun.

**Comment by BirdeeHub** [comment]
Actually I may have already got it

**Comment by BirdeeHub** [comment]
Oh. That other test is only failing because Im running it straight from opening the file rather than serving it, so it doesnt know if it needs to start websocket with http or https.

Ran the tests after serving with python3 http.server and it passes. So, all good, I guess Ill push this and maybe fix the other while im at it? Not sure it actually counts as bug but may as well?
