### ISSUE TITLE
on click toggle [@checked] on <input[type='checkbox']:not(checked)/> works in playground but not elsewhere

### ISSUE THREAD

**Issue by mkgn** [bigskysoftware/_hyperscript#584]
playground html i tried

```
<div>
<button _="on click toggle [@checked] on <input[type='checkbox']:not(checked)/>" >check all</button>
<input type="checkbox" class="ctrl"/>
<input type="checkbox" class="ctrl"/>
<input type="checkbox" class="ctrl"/>
</div>
```

check-all toggles all the checkboxes as expected. However when i do the same in my application it gives me below error

```
on click toggle between [@checked] on <ul#moduleSelector input[type='checkbox']:not(checked)/>
                        ^^
 Error: Expected 'and' but found '[@checked]'
```

according to documentation toggle works with classes only. Then, how come the above works in playground? I am using hyperscript 0.9.13. Is playground using a different version?

**Comment by 1cg** [comment]
That's the older, deprecated syntax for toggling attributes, it should still work (we have a test here: https://github.com/bigskysoftware/_hyperscript/blob/e157a693d65fae9bf70318bb048a7b2d3d657a92/test/commands/toggle.js#L41)

The new syntax is:

```applescript
on click toggle @checked on <input[type='checkbox']:not(checked)/>
```

However this can be a little confusing since this toggles the attribute rather than the `checked` value, which behaves differently
